### ISSUE TITLE
change label country scroll top on firefox

### ISSUE THREAD

**Issue by alex3144** [catamphetamine/react-phone-number-input#145] opened 2018-06-25 10:17 UTC
Hello,
I use firefox 60, when I click on the flag to expand the select of country it scrolls to the top of the page. There is no problem with Chrome.

I test on demo page and there are same problem.

Cordially

**Comment by catamphetamine** [comment] 2018-06-25 10:34
Hmm, I can also see this bug in FireFox.
Ok.

**Comment by alex3144** [comment] 2018-06-25 10:36
thx

**Comment by catamphetamine** [comment] 2018-07-11 11:33
@EmirGluhbegovic Use `/native` version until the fix lands (perhaps this month).

**Comment by EmirGluhbegovic** [comment] 2018-07-12 04:45
@catamphetamine Thanks that solves the problem for the moment.

**Comment by catamphetamine** [comment] 2018-07-17 04:30
I was seeing this bug previously, but now I checked and it's not reproducible.
Anyway, I released version `2.0.0` which makes `/native` export the default one and also uses the updated `react-responsive-ui@0.13` for the `/react-responsive-ui` export.

**Comment by catamphetamine** [comment] 2018-07-20 16:19
There has been some discussion in `scroll-into-view-if-needed` repo because we were having scroll-to-top issue in our project (though in Chrome and every browser, not just FireFox).
https://github.com/stipsan/scroll-into-view-if-needed/issues/359
The point is there is a possibility that in some use cases the "scroll into view" feature can behave incorrectly.
In version `2.0` of this library it was using `scroll-into-view-if-needed@2` for `react-responsive-ui` select.
I released version `2.1` which now only supports React >= 16.3 and also reverted to `scroll-into-view-if-needed@1.5`.
For me it seems to be working now.

**Comment by catamphetamine** [comment] 2018-07-25 23:34
So, i updated `scroll-into-view-if-needed` to verson `2.x` again since the bug was fixed by the author.
Reopen this issue in case of any weird scroll behaviour.

**Closed by catamphetamine** 2018-07-25 23:34 UTC
