### ISSUE TITLE
Android switches keyboard on US format on 4th digit

### ISSUE THREAD

**Issue by richardkeller411** [catamphetamine/react-phone-number-input#304] opened 2019-12-09 22:33 UTC
Anyone else see this?

**Comment by catamphetamine** [comment] 2019-12-09 23:02
Can you describe in detail what exactly is happening?

**Comment by richardkeller411** [comment] 2019-12-09 23:33
Yes on the 4th digit android switches from numbers to alpha

**Comment by catamphetamine** [comment] 2019-12-09 23:34
That's not a detailed description.
A proper step-by-step full description of the process is required.

**Comment by catamphetamine** [comment] 2020-02-05 02:00
Closing because there hasn't been a step-by-step reproduction instruction, and no comments from other users.

**Closed by catamphetamine** 2020-02-05 02:00 UTC
