### ISSUE TITLE
OnChange is repeatedly called with undefined instead of the actual phone number

### ISSUE THREAD

**Issue by keithhalterman** [catamphetamine/react-phone-number-input#248] opened 2019-03-18 21:20 UTC
Just upgraded to the latest version (from 0.17.2)
When typing in `PhoneInput` the `onChange` function is called with`undefined`, instead of the actual phone number value. 
 
```js
<PhoneInput
  placeholder="Enter phone number"
  value={ this.state.phone }
  onChange={ phone => this.setState({ phone }) } 
  country={this.state.country}
  countries={['AU', 'CA', 'NZ', 'GB', 'US']}
  onCountryChange={ country => this.setState({ country }) }
/>
```

Update: `PhoneInput` calls `onChange` with the correct argument after you type `+1` followed by several numbers. 
However, if you do not start with the country code, it will always call `onChange` with `undefined`

**Comment by catamphetamine** [comment] 2019-04-23 12:07
> However, if you do not start with the country code, it will always call `onChange` with `undefined`

Hi.
The issue you're having is a weird one because the demo page works as expected and no one else reported such an issue.

**Comment by catamphetamine** [comment] 2019-06-20 18:58
I'm closing this issue for now.
You can provide a link to live demo if you want (something like "jsfiddle" or such).
Or you can post the steps to reproduce the issue on the "Demo" page.

**Closed by catamphetamine** 2019-06-20 18:58 UTC
