### ISSUE TITLE
About prop type error

### ISSUE THREAD

**Issue by kkurno** [catamphetamine/react-phone-number-input#265] opened 2019-06-14 09:06 UTC
react-phone-number-input@^2.3.13:
version "2.3.17"
  resolved "https://registry.yarnpkg.com/react-phone-number-input/-/react-phone-number-input-2.3.17.tgz#1bb1e7222a5bee8ad942d78460c04d4a6b63f00d"
  integrity sha512-oZiED1n0mmCGJ+nRLk46LQfd5Fb/CO52l2c7JzqmZIo24xLUlshcofmh5v1TSx5DhUggQTyO7C/jQdl6QWxm6Q==
  dependencies:
    classnames "^2.2.5"
    input-format "^0.2.2"
    libphonenumber-js "^1.7.19"
    prop-types "^15.7.2"
    react-lifecycles-compat "^3.0.4"
    react-responsive-ui "^0.14.123"

![Screenshot from 2019-06-14 15-42-52](https://user-images.githubusercontent.com/39963228/59497604-fc0a3000-8ebd-11e9-8ebc-72e9cedc6d0b.png)
![Screenshot from 2019-06-14 16-03-17](https://user-images.githubusercontent.com/39963228/59497607-fd3b5d00-8ebd-11e9-8b2f-aea5d05f835a.png)

I'm not sure about this problem but I think it' related to prop-types, webpack or commonjs

**Comment by catamphetamine** [comment] 2019-06-14 11:10
Hmm, I have recently updated `prop-types` package so that `elementType` is supported there.
It's strange that in your case it didn't install that verison.
Can you try reinstalling `react-phone-number-input` package?
If there error doesn't disappear then post your `prop-types` package version.

**Comment by catamphetamine** [comment] 2019-06-14 11:11
Here's the commit:
https://github.com/catamphetamine/react-phone-number-input/commit/e8c684eaaab73762dbd3010b3a1f7e16b0d6ae01#diff-b9cfc7f2cdf78a7f4b91a753d10865a2

**Comment by kkurno** [comment] 2019-06-17 06:40
I see, but I tested it again by
1. remove node_modules, yarn.lock
2. type >> yarn add prop-types, yarn (in terminal)
3. write the code >> import PropTypes from 'prop-types' in my root component file
4. then >> console.log(PropTypes) in the root component
the result display the key "elementType" and it has "isRequired" included.
![Screenshot from 2019-06-14 15-42-52](https://user-images.githubusercontent.com/39963228/59580057-e2552c80-90f9-11e9-886a-684ed542abc2.png)

**Comment by catamphetamine** [comment] 2019-06-17 10:56
Yeah, that's the point: see what version of `prop-types` is installed either in `node_modules/react-phone-number-input/node_modules` or directly in `node_modules`.
Maybe `rm -rf node_modules` and `yarn`.
Looks like a weird issue.

**Comment by catamphetamine** [comment] 2019-06-20 18:56
No one else has reported the issue so far.
Closing for now.

**Closed by catamphetamine** 2019-06-20 18:56 UTC

**Comment by MalikaN** [comment] 2019-07-10 19:09
I'm experiencing the same issue
<img width="858" alt="Screen Shot 2019-07-11 at 12 36 58 AM" src="https://user-images.githubusercontent.com/19464525/60997294-17a90f00-a374-11e9-9a10-d1d2f8f441a6.png">

Package information 
`"react-phone-number-input": "^2.3.19",`

prop-types package version
`"prop-types": "^15.7.2",`

**Comment by catamphetamine** [comment] 2019-07-11 00:03
@MalikaN Can you post the `version` from `node_modules/prop-types`.
And also check if there's no `node_modules/react-phone-number-input/node_modules/prop-types` folder.

**Comment by MalikaN** [comment] 2019-07-11 02:02
@catamphetamine  node_modules/prop-types/package.json - `"version": "15.7.2"`

and there's no `node_module` folder inside `react-phone-number-input`

**Comment by catamphetamine** [comment] 2019-07-11 02:07
@MalikaN Ok, mine says `"version": "15.7.2"` too.
Now go to `node_modules/prop-types/index.js`.
Mine looks like this:

```js
/**
 * Copyright (c) 2013-present, Facebook, Inc.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
 */

if (process.env.NODE_ENV !== 'production') {
  var ReactIs = require('react-is');

  // By explicitly using `prop-types` you are opting into new development behavior.
  // http://fb.me/prop-types-in-prod
  var throwOnDirectAccess = true;
  module.exports = require('./factoryWithTypeCheckers')(ReactIs.isElement, throwOnDirectAccess);
} else {
  // By explicitly using `prop-types` you are opting into new production behavior.
  // http://fb.me/prop-types-in-prod
  module.exports = require('./factoryWithThrowingShims')();
}
```

You can add `console.log('@@@@@@@@ TEST')` there somewhere.
For example, in the `if` or in the `else`.
If it goes into `if` then it will be `./factoryWithTypeCheckers.js`.
Otherwise it's `./factoryWithThrowingShims.js`.
Tell me which one it is for you.

**Comment by MalikaN** [comment] 2019-07-11 06:14
@catamphetamine my code looks the same. So i added console.logs 
```
if (process.env.NODE_ENV !== 'production') {
    var ReactIs = require('react-is');
        Console.log('Local')
    // By explicitly using `prop-types` you are opting into new development behavior.
    // http://fb.me/prop-types-in-prod
    var throwOnDirectAccess = true;
    module.exports = require('./factoryWithTypeCheckers')(ReactIs.isElement, throwOnDirectAccess);
} else {
    Console.log('Production')
    // By explicitly using `prop-types` you are opting into new production behavior.
    // http://fb.me/prop-types-in-prod
    module.exports = require('./factoryWithThrowingShims')();
}
```
when i run it locally, `Console.log('Local')`  and on production i get `Console.log('Production')`

**Comment by catamphetamine** [comment] 2019-07-11 15:53
I see, so it uses this module.
Well, you could add a line after `module.exports = ` then.
Something like `console.log('@@@@@@@', module.exports.elementType)`.
See if it's defined.
If it's defined then you could continue adding `console.log()`s in `react-phone-number-input/modules/PhoneInput.js` so see if `PropTypes.elementType` is defined there.

**Comment by rhys-vdw** [comment] 2019-08-12 01:38
I'm also having this issue. It seems that your library depends on 15.7.2, which is what I have in my `react-phone-number-input/node_modules/prop-types`.

**Comment by rhys-vdw** [comment] 2019-08-12 01:39
Can I suggest reopening this issue?

**Comment by catamphetamine** [comment] 2019-08-12 12:43
> Can I suggest reopening this issue?

Reopening this issue wouldn't move anything forward.
You can debug the issue as I described in the above comment.
I won't be looking into this so the only way it could be resolved is by someone else finding the cause.

**Comment by joge17** [comment] 2019-09-05 15:07
Is there no solution for this issue?

**Comment by catamphetamine** [comment] 2019-09-05 15:07
@joge17 Until someone experiencing the issue finds the cause there won't be one.
