### ISSUE TITLE
Even if we pass the country flag value, the preselected country value is overriding it

### ISSUE THREAD

**Issue by Shivangi-agarwal-1303** [catamphetamine/react-phone-number-input#163] opened 2018-07-24 15:41 UTC
this.props value has the correct country name which is passed by the user.
But once it calls the function  –  generate_country_select_options , the value is changing to pre_selected_country .
Due to which this.state contains the value of preselected country. But it should consider the value for this.props.country

**Comment by catamphetamine** [comment] 2018-07-24 16:16
Don't understand.
Describe in more detail.

**Comment by Shivangi-agarwal-1303** [comment] 2018-07-25 06:18
This issue is coming when we try to save few phone number which have same area and country code. Actually there are few countries, in which few numbers are valid in all the country. But even if user supplies the appropriate flag for the country , the country icon is again changing to preselected or default country. Probably instead of giving preference to the country supplied in parameters it takes the country selected by default when number is written in the component.
For Eg:-

1.  If we save a number - +44 908 668 0999 with Jersey flag and when we try to retrieve it shows United Kingdom flag.

2. If we save the number   +1 246 431 0179  with Anguilla flag and when we try to retrieve it back it changes to Barbados.


In PhoneInput.js file , we receive props from the component, in those props all the values are populating correctly as we pass for the country and phone number.  

But in line 86 :- 
var pre_selected_country = (0, _inputControl.getPreSelectedCountry)(parsed_number, country, countries, international, metadata);

pre_selected_country is coming as the country which comes by default when we type the number even when the country parameter  is having value. 

And then in line no :- 89

_this.state = {
			// Workaround for `this.props` inside `getDerivedStateFromProps()`.
			props: _this.props,

			// The country selected.
			country: pre_selected_country,
......

Its assigning pre_selected_country value to the country. Due to which its not considering the value passed by the user. Its considering the value which comes automatically when we type the number.

**Comment by catamphetamine** [comment] 2018-07-25 08:46
@Shivangi-agarwal-1303 
So, let's start from simple things.

> If we save a number - +44 908 668 0999 with Jersey flag and when we try to retrieve it shows United Kingdom flag.

I open the demo and paste "+44 908 668 0999" there and it shows "GB" flag.
This is the correct result because Google's demo also shows "GB" for this number:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B44+908+668+0999
No "Jersey" here (whatever it is).

> If we save the number +1 246 431 0179 with Anguilla flag and when we try to retrieve it back it changes to Barbados.

Same for this number, it is from Barbados:
https://libphonenumber.appspot.com/phonenumberparser?number=%2B1+246+431+0179

If you disagree with the parsed country code then post an issue in Google's repo.

> pre_selected_country is coming as the country which comes by default when we type the number even when the country parameter is having value.

Yes, it always re-writes the `country` property if `value` is provided and if the country parsed from `value` is different from the "default country" (`country` property) provided.

**Comment by Shivangi-agarwal-1303** [comment] 2018-07-25 09:01
If we save a number - +44 908 668 0999 with Jersey flag and when we try to retrieve it shows United Kingdom flag.
So coming to this point we have entered this number. And then we have changed to Jersey flag. And this is a valid phone number for Jersey. When we try to save this , and retrieving back its changing to GB . (Jersey Flag is JE).

**Comment by catamphetamine** [comment] 2018-07-25 09:10
> And this is a valid phone number for Jersey.

Google doesn't think so.
This library is based on Google's.
Create an issue in Google's repo if you think otherwise.

> Is it a correct behavior?

This is the intended behaviour.

**Comment by Shivangi-agarwal-1303** [comment] 2018-07-25 09:15
If its not a valid number for jersey then why phone component is showing valid after changing the flag to JE ?

**Comment by Shivangi-agarwal-1303** [comment] 2018-07-25 09:20
But we get isValid flag, it a boolean value. True if its valid and False if its not.

**Comment by catamphetamine** [comment] 2018-07-25 09:22
> But we get isValid flag, it a boolean value. True if its valid and False if its not.

Where exactly.

**Comment by catamphetamine** [comment] 2018-07-25 09:33
Format your comments properly, then maybe I look.

**Comment by Shivangi-agarwal-1303** [comment] 2018-07-25 09:34
`return _react2.default.createElement(
				'div',
				{
					style: style,
					className: (0, _classnames2.default)('react-phone-number-input', {
						'react-phone-number-input--invalid': error && indicateInvalid
					}, className) },
				_react2.default.createElement(`

This is line number - 226 of PhoneInput.js file

**Comment by catamphetamine** [comment] 2018-07-25 09:35
> This is line number - 226 of PhoneInput.js file

What's the question.
And don't post the compiled code, post the original source.

**Comment by Shivangi-agarwal-1303** [comment] 2018-07-25 09:44
okay..  I just wanted to show that it shows invalid and valid. Lets drop that part.

Can you please try to save any number for Jersey Flag.
In my Observation we can not save a Jersey flag phone number as it will change to GB

**Comment by catamphetamine** [comment] 2018-07-25 09:45
> Can you please try to save any number for Jersey Flag.

This component doesn't provide any "save" functionality so it's out of scope of this library.

>  In my Observation we can not save a Jersey flag phone number.

No, everyone can "save" anything in any form.

**Comment by Shivangi-agarwal-1303** [comment] 2018-07-25 09:49
Can you please send these parameters in json and check? 
Give country as 'JE' and any valid number of jersey.

**Comment by catamphetamine** [comment] 2018-07-25 09:49
> Can you please send these parameters in json and check?

No.

**Closed by catamphetamine** 2018-07-25 09:49 UTC
