### ISSUE TITLE
[Accessibility] Talkback focus moves to the "Country" combo box twice

### ISSUE THREAD

**Issue by mayukh-ms** [catamphetamine/react-phone-number-input#322] opened 2020-01-20 18:46 UTC
Talkback focus moves to the "Country" combo box twice.

**Environment Details:** 
**Mobile :** Samsung S9
**Android version:** 9
**Browser used:** default browser

**Comment by catamphetamine** [comment] 2020-01-20 20:43
Provide exact reproduction steps and more details on the issue, otherwise it won't do.

**Comment by catamphetamine** [comment] 2020-02-03 08:50
Closing because it's not a critical bug and version `3.x` is the current one.
Also no clear reproduction instructions provided.

**Closed by catamphetamine** 2020-02-03 08:50 UTC
