### ISSUE TITLE
[Accessibility] Voice over is not reading the "Combo box list items" position count information except the selected option

### ISSUE THREAD

**Issue by mayukh-ms** [catamphetamine/react-phone-number-input#323] opened 2020-01-20 19:03 UTC
Voice over is not reading the "Combo box list items" position count information except the selected option. For the selected option, the voice over is able to read its postion as item X out of Y items, but when we navigate to the other options, it doesn't read the positioning information.

**iOS version:** 12.4.1 
**Package version:** 2.3.5
**Browser used:** Default browser

**Comment by catamphetamine** [comment] 2020-01-20 20:44
I didn't check this component with VoiceOver, so you'd have to provide detailed reproduction steps if you want me to possibly look into this some time in future.

**Comment by catamphetamine** [comment] 2020-02-03 08:50
Closing because it's not a critical bug and version `3.x` is the current one.
Also no clear reproduction instructions provided.

**Closed by catamphetamine** 2020-02-03 08:50 UTC
