### ISSUE TITLE
Required props working with styled-components

### ISSUE THREAD

**Issue by Josmolmor** [catamphetamine/react-phone-number-input#317] opened 2020-01-17 12:04 UTC
There are some props that aren't supposed to be required while building the component but if used with `styled-components`, it prompts a warning, like `metadata`, `labels` or `countrySelectComponent`.

![image](https://user-images.githubusercontent.com/45819714/72611117-88d00d00-3929-11ea-9913-c44a9ec66f0e.png)

maybe set them to non-required as they are gonna get a default value anyways?

Thanks for the project, keep it up :)

**Comment by catamphetamine** [comment] 2020-01-17 15:47
What is `styled-components` and what does it do?
Why does it change the props of the component?

**Comment by Josmolmor** [comment] 2020-01-17 15:54
https://styled-components.com/

**Comment by catamphetamine** [comment] 2020-01-17 15:55
Well, whatever that is, if some props are marked as required then they're usually set as `defaultProps`.
If `countrySelectComponent` is not found in props then it means that those "styled components" somehow lost the `defaultProps`, or something like that.

**Closed** 2020-02-03 08:51 UTC

**Comment by mdere-unbound** [comment] 2020-02-03 22:03
I just ran into this issue - @Josmolmor  did you find a solution?

**Comment by catamphetamine** [comment] 2020-02-03 22:04
Note: I won't be fixing this, so the only solution would be someone finding the cause and submitting a pull request.

**Comment by landsman** [comment] 2020-04-01 01:33
@mdere-unbound How did you solved this, please?
