### ISSUE TITLE
[Accessibility] Talkback is reading the placeholder text information twice

### ISSUE THREAD

**Issue by mayukh-ms** [catamphetamine/react-phone-number-input#321] opened 2020-01-20 18:41 UTC
Talkback is reading the placeholder text information twice

**Environment Details:** 
**Mobile :** Samsung S9
**Android version:** 9
**Browser used:** default browser
**Package version:** 2.3.5

**Comment by catamphetamine** [comment] 2020-01-20 20:43
> Talkback is reading the placeholder text information twice

Provide more details, otherwise it's unclear.
What is talkback.
Which placeholder.
What exactly does it read twice.
When exactly does it do so.

**Comment by catamphetamine** [comment] 2020-02-03 08:50
Closing because it's not a critical bug and version `3.x` is the current one.
Also no clear reproduction instructions provided.

**Closed by catamphetamine** 2020-02-03 08:50 UTC
